# gdrive-mount configuration — generated by /gdrive-setup
# Edit this file to change your mount settings.

GDRIVE_REMOTE_NAME="gdrive"
GDRIVE_REMOTE_FOLDER=""
GDRIVE_MOUNT_POINT="/data/users/mkarrmann/gdrive"

# Folders to auto-add to VS Code workspace
VSCODE_FOLDERS=(
    "~/gdrive"
    "~/.claude"
)
