alias k="kubectl"
alias graph="git log --all --decorate --oneline --graph"
alias g="git"
alias gs="git status"
alias gc="git commit"
alias ga="git add"
alias gd="git diff"
alias sl="ls"
alias v="vim"

