load("@fbcode_macros//build_defs:native_rules.bzl", "buck_filegroup")

oncall("confucius")

buck_filegroup(
    name = "skill-resources",
    srcs = glob([
        "**/*.md",
        "scripts/*",
    ]),
    visibility = ["PUBLIC"],
)
