"""Generate Codex config from shared defaults and parsed local overrides."""

import copy
import datetime
import json
import os
import re
import tempfile
from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # Python < 3.11: install tomli in this interpreter.


# Codex updates these tables itself. Keep them across regeneration; explicit
# template/local entries still win. MCPs not owned by our definitions also stay.
STATE_TABLES = ("projects", "tui", "notice", "features", "plugins", "hooks")
GENERATED_HEADER = "# Generated by dotfiles; edit config.local.toml for local overrides.\n"


def codex_home() -> Path:
    home = Path.home()
    configured = Path(os.environ.get("CODEX_HOME") or home / ".codex")
    if configured.match(str(home / ".omnigent/codex-native/*/codex-home")):
        return home / ".codex"
    return configured


def read_config(path: Path) -> dict:
    # A dangling symlink is an error, not an empty config to overwrite.
    if not path.exists() and not path.is_symlink():
        return {}
    return tomllib.loads(path.read_text())


def merge(base: dict, overrides: dict) -> dict:
    result = copy.deepcopy(base)
    for key, value in overrides.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def _key(value: str) -> str:
    if re.fullmatch(r"[A-Za-z0-9_-]+", value):
        return value
    return json.dumps(value, ensure_ascii=False).replace("\x7f", "\\u007f")


def _value(value) -> str:
    # Inline tables cover dictionaries inside arrays without a TOML writer
    # dependency. Ordinary tables are emitted separately below for readability.
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False).replace("\x7f", "\\u007f")
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (datetime.date, datetime.time)):
        return value.isoformat()
    if isinstance(value, list):
        return "[" + ", ".join(_value(item) for item in value) + "]"
    if isinstance(value, dict):
        entries = (f"{_key(k)} = {_value(v)}" for k, v in sorted(value.items()))
        return "{ " + ", ".join(entries) + " }"
    raise TypeError(f"unsupported TOML value: {type(value).__name__}")


def dumps(data: dict) -> str:
    lines = []

    def table(values, path):
        if path:
            lines.extend(["", "[" + ".".join(_key(k) for k in path) + "]"])
        for key, value in sorted(values.items()):
            if not isinstance(value, dict):
                lines.append(f"{_key(key)} = {_value(value)}")
        for key, value in sorted(values.items()):
            if isinstance(value, dict):
                table(value, (*path, key))

    table(data, ())
    text = "\n".join(lines).lstrip() + "\n"
    tomllib.loads(text)  # Validate before any on-disk file is replaced.
    return text


def write_atomic(path: Path, text: str) -> None:
    if not path.is_symlink() and path.exists() and path.read_text() == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w") as stream:
            stream.write(text)
        os.replace(name, path)  # Replace a legacy symlink, never its target.
    finally:
        if os.path.exists(name):
            os.unlink(name)


def _backup(path: Path) -> None:
    fd, name = tempfile.mkstemp(prefix=f"{path.name}.backup-", dir=path.parent)
    with os.fdopen(fd, "wb") as stream:
        stream.write(path.read_bytes())
    print(f"backed up {path} to {name}")


def _differences(current: dict, defaults: dict) -> dict:
    result = {}
    for key, value in current.items():
        if key not in defaults:
            result[key] = copy.deepcopy(value)
        elif isinstance(value, dict) and isinstance(defaults[key], dict):
            delta = _differences(value, defaults[key])
            if delta:
                result[key] = delta
        elif value != defaults[key]:
            result[key] = copy.deepcopy(value)
    return result


def apply_mcps(data: dict, mcps: dict, local: dict, retired=()) -> dict:
    data = copy.deepcopy(data)
    servers = data.setdefault("mcp_servers", {})
    for name in retired:
        servers.pop(name, None)
    for name, spec in mcps.items():
        # Replace managed definitions as a unit so retired args/env disappear.
        servers[name] = {
            k: copy.deepcopy(spec[k])
            for k in ("command", "args", "env")
            if k in spec
        }
    data["mcp_servers"] = merge(servers, local.get("mcp_servers", {}))
    return data


def generate_config(dotfiles: Path, mcps: dict, *, work: bool = True, retired=()) -> None:
    home = codex_home()
    path = home / "config.toml"
    local_path = home / "config.local.toml"
    template = dotfiles / "codex_config/config.template.toml"
    # Escape the replacement for its position inside a TOML string.
    escaped_home = json.dumps(str(Path.home()), ensure_ascii=False)[1:-1]
    defaults = tomllib.loads(template.read_text().replace("__HOME__", escaped_home))
    if work:
        defaults = merge(defaults, read_config(dotfiles / "codex_config/config.work.toml"))
    current, local = read_config(path), read_config(local_path)
    legacy = dotfiles / "codex_config/config.toml"
    migrate = path.is_symlink() and path.resolve() == legacy.resolve()
    if path.is_symlink() and not migrate:
        raise ValueError(f"unexpected config symlink: {path}; migrate its settings first")

    if migrate:
        saved = _differences(current, defaults)
        for key in ("tui", "notice", "plugins", "hooks"):
            saved.pop(key, None)
        servers = saved.get("mcp_servers", {})
        for name in set(mcps) | set(retired):
            servers.pop(name, None)
        if not servers:
            saved.pop("mcp_servers", None)
        local = merge(saved, local)  # Existing explicit overrides take priority.

    state = {
        key: current[key]
        for key in (*STATE_TABLES, "mcp_servers")
        if key in current
    }
    result = merge(merge(state, defaults), local)
    result.setdefault("projects", {}).setdefault(str(dotfiles), {"trust_level": "trusted"})
    result = apply_mcps(result, mcps, local, retired)
    rendered = GENERATED_HEADER + dumps(result)
    local_text = "# Local overrides preserved from the legacy Codex config.\n" + dumps(local)

    # Parse and render everything before touching either input. Keep backups
    # before the one-time migration, including an existing local override file.
    if migrate:
        _backup(path)
        if local_path.exists():
            _backup(local_path)
        write_atomic(local_path, local_text)
    write_atomic(path, rendered)
    print(f"generated {path}")
